/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountsAccountsClose } from "../funcs/accountsAccountsClose.js";
import { accountsAccountsCreate } from "../funcs/accountsAccountsCreate.js";
import { accountsAccountsDeposit } from "../funcs/accountsAccountsDeposit.js";
import { accountsAccountsList } from "../funcs/accountsAccountsList.js";
import { accountsAccountsRetrieve } from "../funcs/accountsAccountsRetrieve.js";
import { accountsAccountsTransfer } from "../funcs/accountsAccountsTransfer.js";
import { accountsAccountsUpdateStatus } from "../funcs/accountsAccountsUpdateStatus.js";
import { accountsAccountsWithdraw } from "../funcs/accountsAccountsWithdraw.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Accounts extends ClientSDK {
  /**
   * Create account
   */
  async accountsCreate(
    request: models.CreateAccountRequest,
    options?: RequestOptions,
  ): Promise<operations.AccountsCreateResponse> {
    return unwrapAsync(accountsAccountsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List accounts
   */
  async accountsList(
    userId: string,
    options?: RequestOptions,
  ): Promise<operations.AccountsListResponse> {
    return unwrapAsync(accountsAccountsList(
      this,
      userId,
      options,
    ));
  }

  /**
   * Retrieve account
   */
  async accountsRetrieve(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.AccountsRetrieveResponse> {
    return unwrapAsync(accountsAccountsRetrieve(
      this,
      id,
      options,
    ));
  }

  /**
   * Update account status
   */
  async accountsUpdateStatus(
    id: string,
    updateAccountRequest: models.UpdateAccountRequest,
    options?: RequestOptions,
  ): Promise<operations.AccountsUpdateStatusResponse> {
    return unwrapAsync(accountsAccountsUpdateStatus(
      this,
      id,
      updateAccountRequest,
      options,
    ));
  }

  /**
   * Close account
   */
  async accountsClose(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.AccountsCloseResponse> {
    return unwrapAsync(accountsAccountsClose(
      this,
      id,
      options,
    ));
  }

  /**
   * Deposit into account
   */
  async accountsDeposit(
    id: string,
    depositRequest: models.DepositRequest,
    options?: RequestOptions,
  ): Promise<operations.AccountsDepositResponse> {
    return unwrapAsync(accountsAccountsDeposit(
      this,
      id,
      depositRequest,
      options,
    ));
  }

  /**
   * Withdraw from account
   */
  async accountsWithdraw(
    id: string,
    withdrawRequest: models.WithdrawRequest,
    options?: RequestOptions,
  ): Promise<operations.AccountsWithdrawResponse> {
    return unwrapAsync(accountsAccountsWithdraw(
      this,
      id,
      withdrawRequest,
      options,
    ));
  }

  /**
   * Transfer between accounts
   */
  async accountsTransfer(
    id: string,
    transferRequest: models.TransferRequest,
    options?: RequestOptions,
  ): Promise<operations.AccountsTransferResponse> {
    return unwrapAsync(accountsAccountsTransfer(
      this,
      id,
      transferRequest,
      options,
    ));
  }
}
