/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsTransactionsListByAccount } from "../funcs/transactionsTransactionsListByAccount.js";
import { transactionsTransactionsRetrieve } from "../funcs/transactionsTransactionsRetrieve.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Transactions extends ClientSDK {
  /**
   * List account transactions
   */
  async transactionsListByAccount(
    accountId: string,
    limit?: number | undefined,
    options?: RequestOptions,
  ): Promise<operations.TransactionsListByAccountResponse> {
    return unwrapAsync(transactionsTransactionsListByAccount(
      this,
      accountId,
      limit,
      options,
    ));
  }

  /**
   * Retrieve transaction
   */
  async transactionsRetrieve(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.TransactionsRetrieveResponse> {
    return unwrapAsync(transactionsTransactionsRetrieve(
      this,
      id,
      options,
    ));
  }
}
