/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersUsersCreate } from "../funcs/usersUsersCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Users extends ClientSDK {
  /**
   * Create user
   */
  async usersCreate(
    xEnvironment: models.XEnvironment,
    createUserRequest: models.CreateUserRequest,
    options?: RequestOptions,
  ): Promise<operations.UsersCreateResponse> {
    return unwrapAsync(usersUsersCreate(
      this,
      xEnvironment,
      createUserRequest,
      options,
    ));
  }
}
