/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @rails/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx usersUsersCreate.example.ts
 */

import { Rails } from "@rails/sdk";

const rails = new Rails({
  apiKeyAuth: process.env["RAILS_API_KEY_AUTH"] ?? "",
});

async function main() {
  const result = await rails.users.usersCreate("production", {
    firstName: "Alexanne",
    lastName: "Wehner",
    email: "Myah_Veum19@yahoo.com",
    password: "TXz5lHn_rozuDSn",
  });

  console.log(result);
}

main().catch(console.error);
