workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Rails Founder API:
        inputs:
            - location: ./openapi-founder.yaml
        registry:
            location: registry.speakeasyapi.dev/rails/founder/rails-founder-api
targets:
    rails:
        target: typescript
        source: Rails Founder API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/rails/founder/rails-founder-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
