/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AccountsUpdateStatusRequest = {
  id: string;
  updateAccountRequest: models.UpdateAccountRequest;
};

export type AccountsUpdateStatusResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Account;
};

/** @internal */
export type AccountsUpdateStatusRequest$Outbound = {
  id: string;
  UpdateAccountRequest: models.UpdateAccountRequest$Outbound;
};

/** @internal */
export const AccountsUpdateStatusRequest$outboundSchema: z.ZodType<
  AccountsUpdateStatusRequest$Outbound,
  z.ZodTypeDef,
  AccountsUpdateStatusRequest
> = z.object({
  id: z.string(),
  updateAccountRequest: models.UpdateAccountRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateAccountRequest: "UpdateAccountRequest",
  });
});

export function accountsUpdateStatusRequestToJSON(
  accountsUpdateStatusRequest: AccountsUpdateStatusRequest,
): string {
  return JSON.stringify(
    AccountsUpdateStatusRequest$outboundSchema.parse(
      accountsUpdateStatusRequest,
    ),
  );
}

/** @internal */
export const AccountsUpdateStatusResponse$inboundSchema: z.ZodType<
  AccountsUpdateStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.Account$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function accountsUpdateStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountsUpdateStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountsUpdateStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountsUpdateStatusResponse' from JSON`,
  );
}
