/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AccountsRetrieveRequest = {
  id: string;
};

export type AccountsRetrieveResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Account;
};

/** @internal */
export type AccountsRetrieveRequest$Outbound = {
  id: string;
};

/** @internal */
export const AccountsRetrieveRequest$outboundSchema: z.ZodType<
  AccountsRetrieveRequest$Outbound,
  z.ZodTypeDef,
  AccountsRetrieveRequest
> = z.object({
  id: z.string(),
});

export function accountsRetrieveRequestToJSON(
  accountsRetrieveRequest: AccountsRetrieveRequest,
): string {
  return JSON.stringify(
    AccountsRetrieveRequest$outboundSchema.parse(accountsRetrieveRequest),
  );
}

/** @internal */
export const AccountsRetrieveResponse$inboundSchema: z.ZodType<
  AccountsRetrieveResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.Account$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function accountsRetrieveResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountsRetrieveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountsRetrieveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountsRetrieveResponse' from JSON`,
  );
}
