/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AccountsWithdrawRequest = {
  id: string;
  withdrawRequest: models.WithdrawRequest;
};

export type AccountsWithdrawResponse = {
  headers: { [k: string]: Array<string> };
  result: models.AccountTransactionResult;
};

/** @internal */
export type AccountsWithdrawRequest$Outbound = {
  id: string;
  WithdrawRequest: models.WithdrawRequest$Outbound;
};

/** @internal */
export const AccountsWithdrawRequest$outboundSchema: z.ZodType<
  AccountsWithdrawRequest$Outbound,
  z.ZodTypeDef,
  AccountsWithdrawRequest
> = z.object({
  id: z.string(),
  withdrawRequest: models.WithdrawRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    withdrawRequest: "WithdrawRequest",
  });
});

export function accountsWithdrawRequestToJSON(
  accountsWithdrawRequest: AccountsWithdrawRequest,
): string {
  return JSON.stringify(
    AccountsWithdrawRequest$outboundSchema.parse(accountsWithdrawRequest),
  );
}

/** @internal */
export const AccountsWithdrawResponse$inboundSchema: z.ZodType<
  AccountsWithdrawResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.AccountTransactionResult$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function accountsWithdrawResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountsWithdrawResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountsWithdrawResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountsWithdrawResponse' from JSON`,
  );
}
