/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AccountsCloseRequest = {
  id: string;
};

export type AccountsCloseResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Account;
};

/** @internal */
export type AccountsCloseRequest$Outbound = {
  id: string;
};

/** @internal */
export const AccountsCloseRequest$outboundSchema: z.ZodType<
  AccountsCloseRequest$Outbound,
  z.ZodTypeDef,
  AccountsCloseRequest
> = z.object({
  id: z.string(),
});

export function accountsCloseRequestToJSON(
  accountsCloseRequest: AccountsCloseRequest,
): string {
  return JSON.stringify(
    AccountsCloseRequest$outboundSchema.parse(accountsCloseRequest),
  );
}

/** @internal */
export const AccountsCloseResponse$inboundSchema: z.ZodType<
  AccountsCloseResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.Account$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function accountsCloseResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountsCloseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountsCloseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountsCloseResponse' from JSON`,
  );
}
