/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AccountsDepositRequest = {
  id: string;
  depositRequest: models.DepositRequest;
};

export type AccountsDepositResponse = {
  headers: { [k: string]: Array<string> };
  result: models.AccountTransactionResult;
};

/** @internal */
export type AccountsDepositRequest$Outbound = {
  id: string;
  DepositRequest: models.DepositRequest$Outbound;
};

/** @internal */
export const AccountsDepositRequest$outboundSchema: z.ZodType<
  AccountsDepositRequest$Outbound,
  z.ZodTypeDef,
  AccountsDepositRequest
> = z.object({
  id: z.string(),
  depositRequest: models.DepositRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    depositRequest: "DepositRequest",
  });
});

export function accountsDepositRequestToJSON(
  accountsDepositRequest: AccountsDepositRequest,
): string {
  return JSON.stringify(
    AccountsDepositRequest$outboundSchema.parse(accountsDepositRequest),
  );
}

/** @internal */
export const AccountsDepositResponse$inboundSchema: z.ZodType<
  AccountsDepositResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.AccountTransactionResult$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function accountsDepositResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountsDepositResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountsDepositResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountsDepositResponse' from JSON`,
  );
}
