/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AccountsListRequest = {
  userId: string;
};

export type AccountsListResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<models.Account>;
};

/** @internal */
export type AccountsListRequest$Outbound = {
  user_id: string;
};

/** @internal */
export const AccountsListRequest$outboundSchema: z.ZodType<
  AccountsListRequest$Outbound,
  z.ZodTypeDef,
  AccountsListRequest
> = z.object({
  userId: z.string(),
}).transform((v) => {
  return remap$(v, {
    userId: "user_id",
  });
});

export function accountsListRequestToJSON(
  accountsListRequest: AccountsListRequest,
): string {
  return JSON.stringify(
    AccountsListRequest$outboundSchema.parse(accountsListRequest),
  );
}

/** @internal */
export const AccountsListResponse$inboundSchema: z.ZodType<
  AccountsListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.array(models.Account$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function accountsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountsListResponse' from JSON`,
  );
}
