/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AccountsCreateResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Account;
};

/** @internal */
export const AccountsCreateResponse$inboundSchema: z.ZodType<
  AccountsCreateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.Account$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function accountsCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountsCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountsCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountsCreateResponse' from JSON`,
  );
}
