/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type AccountsTransferRequest = {
  id: string;
  transferRequest: models.TransferRequest;
};

export type AccountsTransferResponse = {
  headers: { [k: string]: Array<string> };
  result: models.TransferResult;
};

/** @internal */
export type AccountsTransferRequest$Outbound = {
  id: string;
  TransferRequest: models.TransferRequest$Outbound;
};

/** @internal */
export const AccountsTransferRequest$outboundSchema: z.ZodType<
  AccountsTransferRequest$Outbound,
  z.ZodTypeDef,
  AccountsTransferRequest
> = z.object({
  id: z.string(),
  transferRequest: models.TransferRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    transferRequest: "TransferRequest",
  });
});

export function accountsTransferRequestToJSON(
  accountsTransferRequest: AccountsTransferRequest,
): string {
  return JSON.stringify(
    AccountsTransferRequest$outboundSchema.parse(accountsTransferRequest),
  );
}

/** @internal */
export const AccountsTransferResponse$inboundSchema: z.ZodType<
  AccountsTransferResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.TransferResult$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function accountsTransferResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountsTransferResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountsTransferResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountsTransferResponse' from JSON`,
  );
}
