/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type TransactionsListByAccountRequest = {
  accountId: string;
  limit?: number | undefined;
};

export type TransactionsListByAccountResponse = {
  headers: { [k: string]: Array<string> };
  result: Array<models.Transaction>;
};

/** @internal */
export type TransactionsListByAccountRequest$Outbound = {
  account_id: string;
  limit?: number | undefined;
};

/** @internal */
export const TransactionsListByAccountRequest$outboundSchema: z.ZodType<
  TransactionsListByAccountRequest$Outbound,
  z.ZodTypeDef,
  TransactionsListByAccountRequest
> = z.object({
  accountId: z.string(),
  limit: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    accountId: "account_id",
  });
});

export function transactionsListByAccountRequestToJSON(
  transactionsListByAccountRequest: TransactionsListByAccountRequest,
): string {
  return JSON.stringify(
    TransactionsListByAccountRequest$outboundSchema.parse(
      transactionsListByAccountRequest,
    ),
  );
}

/** @internal */
export const TransactionsListByAccountResponse$inboundSchema: z.ZodType<
  TransactionsListByAccountResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: z.array(models.Transaction$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function transactionsListByAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<TransactionsListByAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionsListByAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionsListByAccountResponse' from JSON`,
  );
}
