/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type TransactionsRetrieveRequest = {
  id: string;
};

export type TransactionsRetrieveResponse = {
  headers: { [k: string]: Array<string> };
  result: models.Transaction;
};

/** @internal */
export type TransactionsRetrieveRequest$Outbound = {
  id: string;
};

/** @internal */
export const TransactionsRetrieveRequest$outboundSchema: z.ZodType<
  TransactionsRetrieveRequest$Outbound,
  z.ZodTypeDef,
  TransactionsRetrieveRequest
> = z.object({
  id: z.string(),
});

export function transactionsRetrieveRequestToJSON(
  transactionsRetrieveRequest: TransactionsRetrieveRequest,
): string {
  return JSON.stringify(
    TransactionsRetrieveRequest$outboundSchema.parse(
      transactionsRetrieveRequest,
    ),
  );
}

/** @internal */
export const TransactionsRetrieveResponse$inboundSchema: z.ZodType<
  TransactionsRetrieveResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.Transaction$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function transactionsRetrieveResponseFromJSON(
  jsonString: string,
): SafeParseResult<TransactionsRetrieveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionsRetrieveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionsRetrieveResponse' from JSON`,
  );
}
