/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type UsersCreateRequest = {
  xEnvironment: models.XEnvironment;
  createUserRequest: models.CreateUserRequest;
};

export type UsersCreateResponse = {
  headers: { [k: string]: Array<string> };
  result: models.CreateUserResponse;
};

/** @internal */
export type UsersCreateRequest$Outbound = {
  "X-Environment": string;
  CreateUserRequest: models.CreateUserRequest$Outbound;
};

/** @internal */
export const UsersCreateRequest$outboundSchema: z.ZodType<
  UsersCreateRequest$Outbound,
  z.ZodTypeDef,
  UsersCreateRequest
> = z.object({
  xEnvironment: models.XEnvironment$outboundSchema,
  createUserRequest: models.CreateUserRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    xEnvironment: "X-Environment",
    createUserRequest: "CreateUserRequest",
  });
});

export function usersCreateRequestToJSON(
  usersCreateRequest: UsersCreateRequest,
): string {
  return JSON.stringify(
    UsersCreateRequest$outboundSchema.parse(usersCreateRequest),
  );
}

/** @internal */
export const UsersCreateResponse$inboundSchema: z.ZodType<
  UsersCreateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())).default({}),
  Result: models.CreateUserResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

export function usersCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<UsersCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsersCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsersCreateResponse' from JSON`,
  );
}
