/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const AccountStatus = {
  Active: "active",
  Suspended: "suspended",
  Closed: "closed",
} as const;
export type AccountStatus = ClosedEnum<typeof AccountStatus>;

/** @internal */
export const AccountStatus$inboundSchema: z.ZodNativeEnum<
  typeof AccountStatus
> = z.nativeEnum(AccountStatus);
/** @internal */
export const AccountStatus$outboundSchema: z.ZodNativeEnum<
  typeof AccountStatus
> = AccountStatus$inboundSchema;
