/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Account, Account$inboundSchema } from "./account.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Transaction, Transaction$inboundSchema } from "./transaction.js";

export type AccountTransactionResult = {
  account: Account;
  transaction: Transaction;
};

/** @internal */
export const AccountTransactionResult$inboundSchema: z.ZodType<
  AccountTransactionResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  account: Account$inboundSchema,
  transaction: Transaction$inboundSchema,
});

export function accountTransactionResultFromJSON(
  jsonString: string,
): SafeParseResult<AccountTransactionResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountTransactionResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountTransactionResult' from JSON`,
  );
}
