/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { AccountStatus, AccountStatus$inboundSchema } from "./accountstatus.js";
import { AccountType, AccountType$inboundSchema } from "./accounttype.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type Account = {
  id: string;
  accountNumber: string;
  accountType: AccountType;
  organizationId?: string | null | undefined;
  environment: string;
  userId: string;
  adminUserId?: string | null | undefined;
  userRole?: string | null | undefined;
  balance: string;
  currency: string;
  status: AccountStatus;
  createdAt?: Date | null | undefined;
  updatedAt?: Date | null | undefined;
};

/** @internal */
export const Account$inboundSchema: z.ZodType<Account, z.ZodTypeDef, unknown> =
  z.object({
    id: z.string(),
    account_number: z.string(),
    account_type: AccountType$inboundSchema,
    organization_id: z.nullable(z.string()).optional(),
    environment: z.string(),
    user_id: z.string(),
    admin_user_id: z.nullable(z.string()).optional(),
    user_role: z.nullable(z.string()).optional(),
    balance: z.string(),
    currency: z.string(),
    status: AccountStatus$inboundSchema,
    created_at: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
    updated_at: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "account_number": "accountNumber",
      "account_type": "accountType",
      "organization_id": "organizationId",
      "user_id": "userId",
      "admin_user_id": "adminUserId",
      "user_role": "userRole",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  });

export function accountFromJSON(
  jsonString: string,
): SafeParseResult<Account, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Account$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Account' from JSON`,
  );
}
