/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { AccountType, AccountType$outboundSchema } from "./accounttype.js";

export type CreateAccountRequest = {
  accountType: AccountType;
  organizationId?: string | null | undefined;
  environment?: string | null | undefined;
  userId: string;
  currency?: string | undefined;
};

/** @internal */
export type CreateAccountRequest$Outbound = {
  account_type: string;
  organization_id?: string | null | undefined;
  environment?: string | null | undefined;
  user_id: string;
  currency: string;
};

/** @internal */
export const CreateAccountRequest$outboundSchema: z.ZodType<
  CreateAccountRequest$Outbound,
  z.ZodTypeDef,
  CreateAccountRequest
> = z.object({
  accountType: AccountType$outboundSchema,
  organizationId: z.nullable(z.string()).optional(),
  environment: z.nullable(z.string()).optional(),
  userId: z.string(),
  currency: z.string().default("USD"),
}).transform((v) => {
  return remap$(v, {
    accountType: "account_type",
    organizationId: "organization_id",
    userId: "user_id",
  });
});

export function createAccountRequestToJSON(
  createAccountRequest: CreateAccountRequest,
): string {
  return JSON.stringify(
    CreateAccountRequest$outboundSchema.parse(createAccountRequest),
  );
}
