/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type CreateUserResponse = {
  userId: string;
  status: string;
};

/** @internal */
export const CreateUserResponse$inboundSchema: z.ZodType<
  CreateUserResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  user_id: z.string(),
  status: z.string(),
}).transform((v) => {
  return remap$(v, {
    "user_id": "userId",
  });
});

export function createUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateUserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateUserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateUserResponse' from JSON`,
  );
}
