/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DepositRequest = {
  amount: string;
  description?: string | null | undefined;
};

/** @internal */
export type DepositRequest$Outbound = {
  amount: string;
  description?: string | null | undefined;
};

/** @internal */
export const DepositRequest$outboundSchema: z.ZodType<
  DepositRequest$Outbound,
  z.ZodTypeDef,
  DepositRequest
> = z.object({
  amount: z.string(),
  description: z.nullable(z.string()).optional(),
});

export function depositRequestToJSON(depositRequest: DepositRequest): string {
  return JSON.stringify(DepositRequest$outboundSchema.parse(depositRequest));
}
