/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Account, Account$inboundSchema } from "./account.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import { Transaction, Transaction$inboundSchema } from "./transaction.js";

export type TransferResult = {
  fromAccount: Account;
  toAccount: Account;
  transaction: Transaction;
};

/** @internal */
export const TransferResult$inboundSchema: z.ZodType<
  TransferResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  from_account: Account$inboundSchema,
  to_account: Account$inboundSchema,
  transaction: Transaction$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "from_account": "fromAccount",
    "to_account": "toAccount",
  });
});

export function transferResultFromJSON(
  jsonString: string,
): SafeParseResult<TransferResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransferResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransferResult' from JSON`,
  );
}
