/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type TransferRequest = {
  toAccountId: string;
  amount: string;
  description?: string | null | undefined;
};

/** @internal */
export type TransferRequest$Outbound = {
  to_account_id: string;
  amount: string;
  description?: string | null | undefined;
};

/** @internal */
export const TransferRequest$outboundSchema: z.ZodType<
  TransferRequest$Outbound,
  z.ZodTypeDef,
  TransferRequest
> = z.object({
  toAccountId: z.string(),
  amount: z.string(),
  description: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    toAccountId: "to_account_id",
  });
});

export function transferRequestToJSON(
  transferRequest: TransferRequest,
): string {
  return JSON.stringify(TransferRequest$outboundSchema.parse(transferRequest));
}
