/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const TransactionType = {
  Deposit: "deposit",
  Withdrawal: "withdrawal",
  Transfer: "transfer",
  RecurringPayment: "recurring_payment",
  SavingsWithdraw: "savings_withdraw",
} as const;
export type TransactionType = ClosedEnum<typeof TransactionType>;

/** @internal */
export const TransactionType$inboundSchema: z.ZodNativeEnum<
  typeof TransactionType
> = z.nativeEnum(TransactionType);
