/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const TransactionStatus = {
  Pending: "pending",
  Completed: "completed",
  Failed: "failed",
  Cancelled: "cancelled",
} as const;
export type TransactionStatus = ClosedEnum<typeof TransactionStatus>;

/** @internal */
export const TransactionStatus$inboundSchema: z.ZodNativeEnum<
  typeof TransactionStatus
> = z.nativeEnum(TransactionStatus);
