/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";
import {
  TransactionStatus,
  TransactionStatus$inboundSchema,
} from "./transactionstatus.js";
import {
  TransactionType,
  TransactionType$inboundSchema,
} from "./transactiontype.js";

export type Transaction = {
  id: string;
  accountId: string;
  transactionType: TransactionType;
  amount: string;
  currency: string;
  balanceAfter: string;
  recipientAccountId?: string | null | undefined;
  externalRecipientId?: string | null | undefined;
  referenceId?: string | null | undefined;
  description?: string | null | undefined;
  status: TransactionStatus;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const Transaction$inboundSchema: z.ZodType<
  Transaction,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  account_id: z.string(),
  transaction_type: TransactionType$inboundSchema,
  amount: z.string(),
  currency: z.string(),
  balance_after: z.string(),
  recipient_account_id: z.nullable(z.string()).optional(),
  external_recipient_id: z.nullable(z.string()).optional(),
  reference_id: z.nullable(z.string()).optional(),
  description: z.nullable(z.string()).optional(),
  status: TransactionStatus$inboundSchema,
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "account_id": "accountId",
    "transaction_type": "transactionType",
    "balance_after": "balanceAfter",
    "recipient_account_id": "recipientAccountId",
    "external_recipient_id": "externalRecipientId",
    "reference_id": "referenceId",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function transactionFromJSON(
  jsonString: string,
): SafeParseResult<Transaction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Transaction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Transaction' from JSON`,
  );
}
