/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  AccountStatus,
  AccountStatus$outboundSchema,
} from "./accountstatus.js";

export type UpdateAccountRequest = {
  status?: AccountStatus | undefined;
};

/** @internal */
export type UpdateAccountRequest$Outbound = {
  status?: string | undefined;
};

/** @internal */
export const UpdateAccountRequest$outboundSchema: z.ZodType<
  UpdateAccountRequest$Outbound,
  z.ZodTypeDef,
  UpdateAccountRequest
> = z.object({
  status: AccountStatus$outboundSchema.optional(),
});

export function updateAccountRequestToJSON(
  updateAccountRequest: UpdateAccountRequest,
): string {
  return JSON.stringify(
    UpdateAccountRequest$outboundSchema.parse(updateAccountRequest),
  );
}
