/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type WithdrawRequest = {
  amount: string;
  description?: string | null | undefined;
};

/** @internal */
export type WithdrawRequest$Outbound = {
  amount: string;
  description?: string | null | undefined;
};

/** @internal */
export const WithdrawRequest$outboundSchema: z.ZodType<
  WithdrawRequest$Outbound,
  z.ZodTypeDef,
  WithdrawRequest
> = z.object({
  amount: z.string(),
  description: z.nullable(z.string()).optional(),
});

export function withdrawRequestToJSON(
  withdrawRequest: WithdrawRequest,
): string {
  return JSON.stringify(WithdrawRequest$outboundSchema.parse(withdrawRequest));
}
