/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../types/enums.js";

export const XEnvironment = {
  Sandbox: "sandbox",
  Production: "production",
} as const;
export type XEnvironment = ClosedEnum<typeof XEnvironment>;

/** @internal */
export const XEnvironment$outboundSchema: z.ZodNativeEnum<typeof XEnvironment> =
  z.nativeEnum(XEnvironment);
